# Generated by Django 4.0.2 on 2022-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_servic_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='servic',
            name='description',
            field=models.CharField(default=12, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servic',
            name='title',
            field=models.CharField(default=15, max_length=100),
            preserve_default=False,
        ),
    ]
