# Generated by Django 4.0.2 on 2022-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
